### PR TITLE
Edit layout and fix some buttons

### PR DESCRIPTION
**Pull request by Nickbert7**
Old:
image

New:
image

Fixes also the toggle of the "view" and "filter" buttons. (By clicking one of them I got redirected to the homepage)

### CODE REVIEW

**Comment by Nickbert7** [comment]
also disabled wordwrap
image

**Comment by Nickbert7** [comment]
disabled wordwrap and add edit button 
image

**Comment by joshuaboniface** [comment]
Will wait until 10.4.0 drops to rebuild the new version so it's coincident with the release :+1:

**Comment by Nickbert7** [comment]
Then I hope I can find what the issue with 10.4 is...
It seems to be related to https://github.com/jellyfin/jellyfin/pull/1665

**Pull request merged**
