### PR TITLE
Bump Version

### PR DESCRIPTION
**Pull request by Nickbert7**
Bump version as it is working again for 10.4.3

For the nightly or 10.5.0 we might need another fix:
image

### CODE REVIEW

**Comment by dkanada** [comment]
Has anything changed since the last version?

**Comment by Nickbert7** [comment]
This was the issue I was not able to solve in the past🙈
https://github.com/jellyfin/jellyfin-plugin-reports/pull/13

https://github.com/jellyfin/jellyfin-plugin-reports/pull/9#issuecomment-531264569

**Comment by anthonylavado** [comment]
We don’t need to bump the version, as we never actually released version 4 before. This should be fine and working in the catalog?

**Comment by dkanada** [comment]
> we never actually released version 4 before

Yeah, Version 4 seems to exist in the catalog already.

**Comment by Nickbert7** [comment]
Yes, you are right.
I did not see/get v4 as I already had a local version 4 insallted... sorry..

**Comment by dkanada** [comment]
No worries!

**Pull request closed without merging**
